/**
 * @description colors
 * @author 阿怪
 * @date 2024/3/13 15:42
 * @version v1.0.0
 *
 * 江湖的业务千篇一律，复杂的代码好几百行。
 */


export const colors = {
  '立秋': [
    { color: '#88ABDA', name: '窃蓝' },
    { color: '#6F94CD', name: '监德' },
    { color: '#5976BA', name: '苍苍' },
    { color: '#2E59A7', name: '群青' },
    { color: '#98B6C2', name: '白青' },
    { color: '#7F9FAF', name: '竹月' },
    { color: '#66889E', name: '空青' },
    { color: '#547689', name: '太师青' },
    { color: '#EFEFEF', name: '缟羽' },
    { color: '#D8D1C5', name: '香皮' },
    { color: '#C6BEB1', name: '云母' },
    { color: '#AC9F8A', name: '佩玖' },
    { color: '#C0D09D', name: '麹尘' },
    { color: '#938F4C', name: '绿沈' },
    { color: '#7F754C', name: '绞衣' },
    { color: '#595333', name: '素綦' }
  ],
  '芒种': [
    { color: '#D5D1AE', name: '筠雾' },
    { color: '#BFC096', name: '瓷秘' },
    { color: '#A9A886', name: '琬琰' },
    { color: '#92905D', name: '青圭' },
    { color: '#B3B59C', name: '鸣珂' },
    { color: '#A8B092', name: '青玉案' },
    { color: '#A9A773', name: '出岫' },
    { color: '#868C4E', name: '风入松' },
    { color: '#DDBB99', name: '如梦令' },
    { color: '#D2A36C', name: '芸黄' },
    { color: '#BE9457', name: '金埒' },
    { color: '#B4884D', name: '雌黄' },
    { color: '#535164', name: '曾青' },
    { color: '#454659', name: '䒌靘' },
    { color: '#343041', name: '璆琳' },
    { color: '#1E2732', name: '瑾瑜' }
  ],
  '大雪': [
    { color: '#EFC4CE', name: '粉米' },
    { color: '#CE8892', name: '縓缘' },
    { color: '#C35C6A', name: '美人祭' },
    { color: '#B04552', name: '鞓红' },
    { color: '#EEEAD9', name: '米汤娇' },
    { color: '#BFC1A9', name: '草白' },
    { color: '#A9A082', name: '玄校' },
    { color: '#756C4B', name: '綟绶' },
    { color: '#788A6F', name: '雀梅' },
    { color: '#5D7259', name: '油绿' },
    { color: '#4E6548', name: '莓莓' },
    { color: '#3F503B', name: '螺青' },
    { color: '#A4ABD6', name: '暮山紫' },
    { color: '#757CBB', name: '紫苑' },
    { color: '#615EA8', name: '优昙瑞' },
    { color: '#4A4B9D', name: '延维' }
  ],
  '清明': [
    { color: '#A6559D', name: '紫蒲' },
    { color: '#8A1874', name: '赪紫' },
    { color: '#6C216D', name: '齐紫' },
    { color: '#422256', name: '凝夜紫' },
    { color: '#BEC2B3', name: '冻缥' },
    { color: '#9D9D82', name: '春碧' },
    { color: '#919177', name: '执大象' },
    { color: '#79836C', name: '苔古' },
    { color: '#D3CCD6', name: '香炉紫烟' },
    { color: '#9B8EA9', name: '紫菂' },
    { color: '#7E527F', name: '拂紫绵' },
    { color: '#663D74', name: '三公子' },
    { color: '#CB5C83', name: '琅玕紫' },
    { color: '#B83570', name: '红踯躅' },
    { color: '#A73766', name: '魏红' },
    { color: '#903754', name: '魏紫' }
  ],
  '寒露': [
    { color: '#A6BAB1', name: '醽醁' },
    { color: '#819D8E', name: '翠涛' },
    { color: '#778A77', name: '青梅' },
    { color: '#5F766A', name: '翕赩' },
    { color: '#DDB078', name: '九斤黄' },
    { color: '#DA9233', name: '杏子' },
    { color: '#BC6E37', name: '媚蝶' },
    { color: '#9F5221', name: '韎韐' },
    { color: '#8BA3C7', name: '东方既白' },
    { color: '#003D74', name: '绀宇' },
    { color: '#19325F', name: '佛头青' },
    { color: '#1A2847', name: '花青' },
    { color: '#ECD9C7', name: '弗肯红' },
    { color: '#E1C199', name: '赤璋' },
    { color: '#C6A268', name: '茧色' },
    { color: '#B3934B', name: '密陀僧' }
  ],
  '小暑': [
    { color: '#F5B087', name: '骍刚' },
    { color: '#F18F60', name: '赪霞' },
    { color: '#EF845D', name: '赪尾' },
    { color: '#ED6D46', name: '朱柿' },
    { color: '#E0DFC6', name: '天球' },
    { color: '#BFB99C', name: '行香子' },
    { color: '#A99F70', name: '王刍' },
    { color: '#877D52', name: '荩箧' },
    { color: '#954024', name: '赤灵' },
    { color: '#873424', name: '丹秫' },
    { color: '#662B1F', name: '木兰' },
    { color: '#4C1E1A', name: '麒麟竭' },
    { color: '#106898', name: '柔蓝' },
    { color: '#12507B', name: '碧城' },
    { color: '#06436F', name: '蓝采和' },
    { color: '#003460', name: '帝释青' }
  ],
  '小寒': [
    { color: '#F6F9E4', name: '酂白' },
    { color: '#ECEBC2', name: '断肠' },
    { color: '#E1D384', name: '田赤' },
    { color: '#CAB272', name: '黄封' },
    { color: '#BD9683', name: '丁香褐' },
    { color: '#955A42', name: '棠梨褐' },
    { color: '#81492C', name: '朱石栗' },
    { color: '#68361A', name: '枣褐' },
    { color: '#7D929F', name: '秋蓝' },
    { color: '#576470', name: '育阳染' },
    { color: '#3C4654', name: '霁蓝' },
    { color: '#151D29', name: '獭见' },
    { color: '#A4C9CC', name: '井天' },
    { color: '#6CA8AF', name: '正青' },
    { color: '#509296', name: '扁青' },
    { color: '#226B68', name: '䌦色' }
  ],
  '春分': [
    { color: '#EBEEE8', name: '皦玉' },
    { color: '#EBEDDF', name: '吉量' },
    { color: '#E0E0D0', name: '韶粉' },
    { color: '#C7C6B6', name: '霜地' },
    { color: '#D2AF9D', name: '夏籥' },
    { color: '#BC836B', name: '紫磨金' },
    { color: '#B26D5D', name: '檀色' },
    { color: '#9A6655', name: '赭罗' },
    { color: '#EA5514', name: '黄丹' },
    { color: '#D23918', name: '洛神珠' },
    { color: '#C8161D', name: '丹雘' },
    { color: '#A72126', name: '水华朱' },
    { color: '#3271AE', name: '青冥' },
    { color: '#007175', name: '青雘' },
    { color: '#284852', name: '青緺' },
    { color: '#12264F', name: '骐驎' }
  ],
  '立冬': [
    { color: '#FFFBC7', name: '半见' },
    { color: '#F7EEAD', name: '女贞黄' },
    { color: '#ECE093', name: '绢纨' },
    { color: '#D6C560', name: '姜黄' },
    { color: '#88BFB8', name: '繱犗' },
    { color: '#5DA39D', name: '二绿' },
    { color: '#3D8E86', name: '铜青' },
    { color: '#206864', name: '石绿' },
    { color: '#9E8C6B', name: '黄琮' },
    { color: '#887657', name: '茶色' },
    { color: '#6D5C3D', name: '伽罗' },
    { color: '#5A4B3B', name: '苍艾' },
    { color: '#A88787', name: '藕丝褐' },
    { color: '#9E696D', name: '葡萄褐' },
    { color: '#81474C', name: '苏方' },
    { color: '#662B2F', name: '福色' }
  ],
  '夏至': [
    { color: '#CB523E', name: '赩炽' },
    { color: '#B13B2E', name: '石榴裙' },
    { color: '#95302E', name: '朱湛' },
    { color: '#822327', name: '大繎' },
    { color: '#B2B6B6', name: '月魄' },
    { color: '#A7AAA1', name: '不皂' },
    { color: '#7A7B78', name: '雷雨垂' },
    { color: '#686A67', name: '石涅' },
    { color: '#F0C2A2', name: '扶光' },
    { color: '#DB9C5E', name: '椒房' },
    { color: '#D9883D', name: '红友' },
    { color: '#CC5D20', name: '光明砂' },
    { color: '#F5F3F2', name: '山矾' },
    { color: '#EAE5E3', name: '玉頩' },
    { color: '#DFE0D9', name: '二目鱼' },
    { color: '#D4D3CA', name: '明月珰' }
  ],
  '冬至': [
    { color: '#E7CAD3', name: '银红' },
    { color: '#D9A0B3', name: '莲红' },
    { color: '#BB7A8C', name: '紫梅' },
    { color: '#9E4E56', name: '紫矿' },
    { color: '#DAA9A9', name: '咸池' },
    { color: '#CD7372', name: '红䵂' },
    { color: '#A85858', name: '蚩尤旗' },
    { color: '#7C4449', name: '霁红' },
    { color: '#EBE1A9', name: '莺儿' },
    { color: '#E1D279', name: '禹余粮' },
    { color: '#D6BC46', name: '姚黄' },
    { color: '#BE8A2F', name: '蛾黄' },
    { color: '#796860', name: '濯绛' },
    { color: '#585248', name: '墨黪' },
    { color: '#46433B', name: '驖骊' },
    { color: '#31322C', name: '京元' }
  ],
  '立夏': [
    { color: '#C3D94E', name: '青粲' },
    { color: '#B7D332', name: '翠缥' },
    { color: '#9EBC19', name: '人籁' },
    { color: '#84A729', name: '水龙吟' },
    { color: '#DFCEB4', name: '地籁' },
    { color: '#BFA782', name: '大块' },
    { color: '#B49B7F', name: '养生主' },
    { color: '#94784F', name: '大云' },
    { color: '#BEC2BC', name: '溶溶月' },
    { color: '#A8A19C', name: '绍衣' },
    { color: '#92897B', name: '石莲褐' },
    { color: '#70695D', name: '黑朱' },
    { color: '#F29A76', name: '朱颜酡' },
    { color: '#ED6D3D', name: '苕荣' },
    { color: '#E94829', name: '檎丹' },
    { color: '#E60012', name: '丹罽' }
  ],
  '谷雨': [
    { color: '#DCC7E1', name: '昌荣' },
    { color: '#BBA1CB', name: '紫薄汗' },
    { color: '#A67EB7', name: '茈藐' },
    { color: '#7D5284', name: '紫紶' },
    { color: '#A8BF8F', name: '苍葭' },
    { color: '#68945C', name: '庭芜绿' },
    { color: '#4C8045', name: '翠微' },
    { color: '#446A37', name: '翠虬' },
    { color: '#AED0EE', name: '碧落' },
    { color: '#6E9BC5', name: '挼蓝' },
    { color: '#354E6B', name: '青雀头黛' },
    { color: '#13393E', name: '螺子黛' },
    { color: '#BD8253', name: '露褐' },
    { color: '#945635', name: '檀褐' },
    { color: '#804C2E', name: '緅絺' },
    { color: '#5B3222', name: '目童子' }
  ],
  '霜降': [
    { color: '#D12920', name: '银朱' },
    { color: '#AB1D22', name: '胭脂虫' },
    { color: '#8F1D22', name: '朱樱' },
    { color: '#631216', name: '爵头' },
    { color: '#BDB2B2', name: '甘石' },
    { color: '#91828F', name: '迷楼灰' },
    { color: '#6A5B6D', name: '鸦雏' },
    { color: '#5C4F55', name: '烟墨' },
    { color: '#F8C6B5', name: '十样锦' },
    { color: '#DA9E8C', name: '檀唇' },
    { color: '#D77F66', name: '琼琚' },
    { color: '#B15A43', name: '棠梨' },
    { color: '#DFD7C2', name: '蜜合' },
    { color: '#D4C1A6', name: '假山南' },
    { color: '#BEA78B', name: '紫花布' },
    { color: '#99806C', name: '沉香' }
  ],
  '大暑': [
    { color: '#E3ADB9', name: '夕岚' },
    { color: '#CF929E', name: '雌霓' },
    { color: '#B27777', name: '绛纱' },
    { color: '#A35F65', name: '茹藘' },
    { color: '#EDF1BB', name: '葱青' },
    { color: '#E3EB98', name: '少艾' },
    { color: '#D8DE8A', name: '绮钱' },
    { color: '#CDD171', name: '翠樽' },
    { color: '#D4BF89', name: '石蜜' },
    { color: '#BFA670', name: '沙饧' },
    { color: '#AA8E59', name: '巨吕' },
    { color: '#896D47', name: '吉金' },
    { color: '#BED2BB', name: '山岚' },
    { color: '#9BB496', name: '渌波' },
    { color: '#81A380', name: '青楸' },
    { color: '#698E6A', name: '菉竹' }
  ],
  '大寒': [
    { color: '#995D7F', name: '紫府' },
    { color: '#814662', name: '地血' },
    { color: '#602641', name: '芥拾紫' },
    { color: '#420B2F', name: '油紫' },
    { color: '#EBE3C7', name: '骨缥' },
    { color: '#CAC5A0', name: '青白玉' },
    { color: '#92896B', name: '绿豆褐' },
    { color: '#665F4D', name: '冥色' },
    { color: '#DDC5B8', name: '肉红' },
    { color: '#BEA89D', name: '珠子褐' },
    { color: '#8F6D5F', name: '鹰背褐' },
    { color: '#694B3C', name: '麝香褐' },
    { color: '#C8B6BB', name: '石英' },
    { color: '#9C8D9B', name: '银褐' },
    { color: '#9D858F', name: '烟红' },
    { color: '#76555D', name: '紫诰' }
  ],
  '秋分': [
    { color: '#D5E3D4', name: '卵色' },
    { color: '#CAD7C5', name: '葭菼' },
    { color: '#BECAB7', name: '冰台' },
    { color: '#B3BDA9', name: '青古' },
    { color: '#C0AD5E', name: '栾华' },
    { color: '#AA9649', name: '大赤' },
    { color: '#8F3D2C', name: '佛赤' },
    { color: '#683632', name: '蜜褐' },
    { color: '#4994C4', name: '孔雀蓝' },
    { color: '#4182A4', name: '吐绶蓝' },
    { color: '#32788A', name: '鱼师青' },
    { color: '#006D87', name: '软翠' },
    { color: '#EAEEF1', name: '浅云' },
    { color: '#D4DDE1', name: '素采' },
    { color: '#BDCBD2', name: '影青' },
    { color: '#B2BFC3', name: '逍遥游' }
  ],
  '雨水': [
    { color: '#F9D3E3', name: '盈盈' },
    { color: '#ECB0C1', name: '水红' },
    { color: '#DD7694', name: '苏梅 ' },
    { color: '#A76283', name: '紫茎屏风' },
    { color: '#BEB1AA', name: '葭灰' },
    { color: '#B49273', name: '黄埃' },
    { color: '#A46244', name: '老僧衣' },
    { color: '#6B5458', name: '玄天' },
    { color: '#E5A84B', name: '黄河琉璃' },
    { color: '#E18A3B', name: '库金' },
    { color: '#984F31', name: '缊韨' },
    { color: '#7C461E', name: '紫瓯' },
    { color: '#C0D695', name: '欧碧' },
    { color: '#A9BE7B', name: '春辰' },
    { color: '#779649', name: '碧山' },
    { color: '#4F6F46', name: '青青' }
  ],
  '处暑': [
    { color: '#F0CFE3', name: '退红' },
    { color: '#E4B8D5', name: '樱花' },
    { color: '#CE93BF', name: '丁香' },
    { color: '#BA79B1', name: '木槿' },
    { color: '#C9CFC1', name: '余白' },
    { color: '#A8B78C', name: '兰苕' },
    { color: '#90A07D', name: '碧滋' },
    { color: '#6C8650', name: '葱倩' },
    { color: '#A2D2E2', name: '云门' },
    { color: '#87C0CA', name: '西子' },
    { color: '#5AA4AE', name: '天水碧' },
    { color: '#108B96', name: '法翠' },
    { color: '#EAD89A', name: '桑蕾' },
    { color: '#D5B45C', name: '太一余粮' },
    { color: '#BF9C46', name: '秋香' },
    { color: '#AA8534', name: '老茯神' }
  ],
  '小满': [
    { color: '#E2A2AC', name: '彤管' },
    { color: '#DD6B7B', name: '渥赭' },
    { color: '#C25160', name: '唇脂' },
    { color: '#B81A35', name: '朱孔阳' },
    { color: '#6A8D52', name: '石发' },
    { color: '#5D8351', name: '漆姑' },
    { color: '#4F794A', name: '芰荷' },
    { color: '#2A6E3F', name: '官绿' },
    { color: '#D4C9AA', name: '仙米' },
    { color: '#B4A379', name: '黄螺' },
    { color: '#9E8358', name: '降真香' },
    { color: '#81663B', name: '远志' },
    { color: '#F2C867', name: '嫩鹅黄' },
    { color: '#D3A237', name: '鞠衣' },
    { color: '#D08635', name: '郁金裙' },
    { color: '#9F6027', name: '黄流' }
  ],
  '小雪': [
    { color: '#DE82A7', name: '龙膏烛' },
    { color: '#CC73A0', name: '黪紫' },
    { color: '#B95A89', name: '胭脂水' },
    { color: '#B0436F', name: '胭脂紫' },
    { color: '#E67762', name: '小红' },
    { color: '#DD6B4F', name: '岱赭' },
    { color: '#D24735', name: '鹤顶红' },
    { color: '#B93A26', name: '朱殷' },
    { color: '#D4E5EF', name: '月白' },
    { color: '#BCD4E7', name: '星郎' },
    { color: '#A3BBDB', name: '晴山' },
    { color: '#8AABCC', name: '品月' },
    { color: '#9E8368', name: '明茶褐' },
    { color: '#906C4A', name: '荆褐' },
    { color: '#7C5B3E', name: '驼褐' },
    { color: '#72453A', name: '椒褐' }
  ],
  '惊蛰': [
    { color: '#BA5B49', name: '赤缇' },
    { color: '#A64036', name: '朱草' },
    { color: '#9E2A22', name: '綪茷' },
    { color: '#7C191E', name: '顺圣' },
    { color: '#F6BEC8', name: '桃夭' },
    { color: '#F091A0', name: '杨妃' },
    { color: '#DC6B82', name: '长春' },
    { color: '#C35C5D', name: '牙绯' },
    { color: '#FEDC5E', name: '黄栗留' },
    { color: '#FAC03D', name: '栀子' },
    { color: '#DB9B34', name: '黄不老' },
    { color: '#C67915', name: '柘黄' },
    { color: '#9AA7B1', name: '青鸾' },
    { color: '#6B798E', name: '菘蓝' },
    { color: '#45465E', name: '青黛' },
    { color: '#2C2F3B', name: '绀蝶' }
  ],
  '白露': [
    { color: '#F5F2E9', name: '凝脂' },
    { color: '#EAE4D1', name: '玉色' },
    { color: '#DFD6B8', name: '黄润' },
    { color: '#D5C8A0', name: '缣缃' },
    { color: '#86908A', name: '蕉月' },
    { color: '#6B7D73', name: '千山翠' },
    { color: '#555F4D', name: '结绿' },
    { color: '#45493D', name: '绿云' },
    { color: '#D3CBC5', name: '藕丝秋半' },
    { color: '#C8B5B3', name: '苍烟落照' },
    { color: '#928187', name: '红藤杖' },
    { color: '#594C57', name: '紫鼠' },
    { color: '#C4B798', name: '黄粱' },
    { color: '#A58A5F', name: '蒸栗' },
    { color: '#7C623F', name: '射干' },
    { color: '#644D31', name: '油葫芦' }
  ],
  '立春': [
    { color: '#FFF799', name: '黄白游' },
    { color: '#FFEE6F', name: '松花' },
    { color: '#ECD452', name: '缃叶' },
    { color: '#B6A014', name: '苍黄' },
    { color: '#D5EBE1', name: '天缥' },
    { color: '#B1D5C8', name: '沧浪' },
    { color: '#99BCAC', name: '苍筤' },
    { color: '#80A492', name: '缥碧' },
    { color: '#8B7042', name: '流黄' },
    { color: '#775039', name: '栗壳' },
    { color: '#5F4321', name: '龙战' },
    { color: '#422517', name: '青骊' },
    { color: '#F3A694', name: '海天霞' },
    { color: '#EE7959', name: '缙云' },
    { color: '#BA5140', name: '纁黄' },
    { color: '#C12C1F', name: '珊瑚赫' }
  ]
}

